version: '2'
services:
  db:
    restart: always
    image: rotschopf/rpi-postgres:9.5.4
#    volumes:
#      - postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
  backend:
    restart: always
    image: pvardanega/rpi-lesspass-backend:latest
    expose:
      - '8000'
    ports:
      - '8000:8000'
    volumes:
      - www:/backend/www
    links:
      - db
    env_file:
      - .env
    environment:
      DATABASE_ENGINE: 'django.db.backends.postgresql'
      DATABASE_NAME: 'postgres'
      DATABASE_USER: 'postgres'
      DATABASE_HOST: 'db'
      DATABASE_PORT: '5432'
  frontend:
    restart: always
    image: pvardanega/rpi-lesspass-frontend
    ports:
      - '8080:8080'
volumes:
  www:
